<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfadUeT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfadUeT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUfadUeT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUfadUeT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUfadUeT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UfadUeT',
    'container.build_id' => '462a984e',
    'container.build_time' => 1572952143,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfadUeT');
