<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\frontController' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\frontController.php';

return $this->services['App\\Controller\\frontController'] = new \App\Controller\frontController();
