acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }

acme_hello_homepage_without_param:
    pattern:  /
    defaults: { _controller: AcmeHelloBundle:Default:index0 }