parameters:
#    paradigm.example.class: Acme\ParadigmBundle\Example

services:
#    paradigm.example:
#        class: %paradigm.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
