blog_admin_home:
    pattern: /
    defaults: { _controller: TutoBlogBundle:Admin:index }
    requirements:
        _method: GET
blog_admin_ajouterArticle:
    pattern: /ajouter
    defaults: { _controller: TutoBlogBundle:AdminArticle:ajouter }
    requirements:
        _method: GET|POST
blog_admin_editerArticle:
    pattern: /editer/{id}
    defaults: { _controller: TutoBlogBundle:AdminArticle:editer }
    requirements:
        id: \d+
        _method: GET|POST
blog_admin_supprimerArticle:
    pattern: /supprimer/{id}
    defaults: { _controller: TutoBlogBundle:AdminArticle:supprimer }
    requirements:
        id: \d+
        _method: DELETE