Acme\ParadigmBundle\Entity\images:
    type: entity
    table: null
    repositoryClass: Acme\ParadigmBundle\Entity\imagesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        workId:
            type: integer
            column: work_id
    lifecycleCallbacks: {  }
