Acme\ParadigmBundle\Entity\users:
    type: entity
    table: null
    repositoryClass: Acme\ParadigmBundle\Entity\usersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
    lifecycleCallbacks: {  }
