parameters:
#    tuto_blog.example.class: Tuto\BlogBundle\Example

services:
#    tuto_blog.example:
#        class: %tuto_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
