<?php

namespace Acme\ParadigmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * usersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usersRepository extends EntityRepository
{
}
