<?php

namespace Acme\ParadigmBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * worksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class worksRepository extends EntityRepository
{
}
